### ISSUE TITLE
Issue 1 - Add Collisions to Player in Level 1

### ISSUE THREAD

**Issue by mrabone94** [mrabone94/AstonAdventure#1]
**Issue Start Date**
15th February 2019

**Initial Description**
Creating first issue for adding collisions to the game. I'm currently working on breaking down the objects in  to tile sets.

**Comment by mrabone94** [comment]
Updated buildings so they're now tilesets

@chrisgrub whenever you're available can you add the collisions to the tiles on the outside of the buildings or let me know if it's not working for you?

**Comment by JodieAsh** [comment]
Discovered another issue that prevents this issue from being resolved. 
See issue #12

**Comment by JodieAsh** [comment]
Been looking into this and I'm really not sure what's going on here. 
Checking every layer #12  did not fix the issue. 

I read somewhere that our 'collision' property has to be a property of the tiles not the 'tile set' and not the 'layer' - however I still cannot get this working.

**Comment by JodieAsh** [comment]
After some investigating I have discovered that: 

1) We have to select all tiles in the tile-set and then add the 'Collision' property to the tiles instead of editing the properties of the 'tile-set' - we have to change the properties of every tile within the tile-set.

2) The tile size is DIFFERENT in level one than it is in level two. 
In level one the tile size is '16' and in level two the tile size is '64'.
The code requires the tile width and the tile height (which are currently different between levels).
